name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          repository: actions/dependency-review-action
          ref: max-comment-length
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: 'Dependency Review'
        uses: ./.github/actions/dependency-review-action
        with:
          comment-summary-in-pr: always
