name: Simple Echo


on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: self-hosted

    steps:
      - name: Echo
        run: echo 'hello world'
          
